### ISSUE TITLE
Error when clicking on spiderfied pin

### ISSUE THREAD

**Issue by kushal-jain-shipsy** [nazka/mapbox-gl-js-spiderfy#13]
I am getting the following error when I click on spiderfied pin:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/91045896/230881053-40860cda-1b0a-44dc-8635-9d748f8e5e14.png">

**Comment by simondriesen** [comment]
Hello, I'm not able to reproduce  your issue with the provided information. Could you provide me with the maplibre version you're using and the spiderfy options you use? Also make sure your source has the [cluster](https://maplibre.org/maplibre-style/sources/#geojson-cluster) option set to true.
