### ISSUE TITLE
Feature request: spiderClusterLayout

### ISSUE THREAD

**Issue by bracketsberlin** [nazka/mapbox-gl-js-spiderfy#14]
Hi there,
I just discovered your awesome spiderfy plugin today and am very thankful you made it public!

On my original maplibre map I used a two different layers for my clusters and the clustered markers itself (see screenshot):
<img width="562" alt="Screenshot 2023-08-14 at 14 35 11" src="https://github.com/nazka/map-gl-js-spiderfy/assets/20646553/f7b9e99f-3a63-4d75-a222-61e18fa390a4">

At the moment it looks like your plugin simply uses the layout of the spidered markers (or whichever layer one applies the plugin to) for the clusters. It would be awesome if one could define a `spiderClusterLayout`. Or is this already somehow possible?

Cheers,
Tobi

**Comment by simondriesen** [comment]
Hey Tobi,

If I understand correctly you want the unclustered markers be styled differently than the cluster markers while using one layer?

I didn't foresee an option for this at the moment so you can only do this by using two layers (as in [Maplibre's cluster example](https://maplibre.org/maplibre-gl-js/docs/examples/cluster/)):
```js
map.addLayer({
  'id': 'clusters',
  'type': 'symbol',
  'source': 'markers',
  'filter': ['has', 'point_count'], // layer with style for clustered points
  'layout': {
    'icon-image': 'cluster',
    'icon-allow-overlap': true,
  }
});
    
map.addLayer({
  'id': 'markers',
  'type': 'circle',
  'source': 'markers',
  'filter': ['!', ['has', 'point_count']], // layer with style for unclustered points
  'paint': {
    'circle-color': 'red',
    'circle-radius': 10
  }
});
    
const spiderfy = new Spiderfy(map, {
  onLeafClick: f => console.log(f),
  minZoomLevel: 12,
  zoomIncrement: 2,
}); // create a new spiderfy object

spiderfy.applyTo('clusters');
```

Would this work for you?

Regards,
Simon
