### ISSUE TITLE
Samples are not working anymore

### ISSUE THREAD

**Issue by stylusdotnet** [nazka/mapbox-gl-js-spiderfy#17]
As mentioned in the title, samples are not working anymore. 

I also couldn't get it to work in my project.

It could be a breaking change in the maplibre version, I am not sure.

**Comment by simondriesen** [comment]
Thanks for the heads-up! It seems the latest Maplibre version (4.0.0) that was released last week breaks the demo.

I will look into it, in the meantime the latest supported Maplibre version is 3.6.2.
