### ISSUE TITLE
Can you consider adding "type": "module" to the package.json of the project?

### ISSUE THREAD

**Issue by dragn-dev** [nazka/mapbox-gl-js-spiderfy#22]
Because when I try to import Spiderfy I get an error that says "Unexpected token 'export'".

**Comment by simondriesen** [comment]
Thanks for the suggestion, I would like some more information so I can beter understand what you are dealing with.

Are you using `require` or `import` to get the package? I have only tested `import` so far but maybe I could support both.

**Comment by dragn-dev** [comment]
Import/Require both don't work for me. I try importing it and initializing it but all I get is an error: "Unexpected token 'export'".

**Comment by simondriesen** [comment]
I have added `"type": "module"` to the package.json, hopefully this solves your issue. I'm not quite sure why you are having this issue but as long as you are the only one there is not much use for me to look into it more.
