### ISSUE TITLE
spiderLeavesLayout 'text-field' property not working as expected.

### ISSUE THREAD

**Issue by dejandiklic** [nazka/mapbox-gl-js-spiderfy#24]
When attempting to add text over an icon using the spiderfy feature, I expected the text to be displayed over the spider leaf. However, it is currently being shown in the central node, which also causes the leaf icon rendering to break.

Steps to Reproduce

1. Initialize spiderfy on a Mapbox GL map.
2. Configure the spiderLeavesPaint and spiderLeavesLayout properties to add text and icons.
3. Apply spiderfy to a clustered layer.

Source and Layer Information in use:
- Source type: cluster
- Layer type: symbol

Expected Behavior
The text should be displayed over the spider leaf icon as specified.
![image](https://github.com/user-attachments/assets/2898120f-b5cb-443e-9cb2-37f4b0f0b1f0)

Actual Behavior
The text appears in the central node, and the icon rendering is broken.
![image](https://github.com/user-attachments/assets/19cbc529-14c8-4e2e-b8b6-25a466bc5878)

Versions
"@nazka/map-gl-js-spiderfy": "^1.2.2"
"mapbox-gl": "^3.4.0"

Relevant code:
```
const spiderfy = new Spiderfy(map, {
    onLeafClick: f => console.log(f),
    minZoomLevel: 12,
    zoomIncrement: 2,
    spiderLeavesPaint: {
        'text-color':'black',
        },
    spiderLeavesLayout:{
        'icon-image': [
        'case',
        ['boolean', ['get', 'crewType'], false], mainMapAssets.groupIcon,
        mainMapAssets.initials,
        ],
        'text-size': 12,
        'text-field':"test"
    }
});
spiderfy.applyTo('fieldPerformer-layer-clustered');
```

If needed I will provide aditional info. Thanks.

**Comment by simondriesen** [comment]
Thanks for the detailed problem description. Weird that nobody seems to have ran into this issue before.

I just released a new version of this package that should hopefully resolve your issue.

**Comment by dejandiklic** [comment]
Thank you so much for the swift and effective fix! I appreciate the record time in which you addressed the issue. Your help has resolved the problem perfectly, and everything is now working as expected.
