### ISSUE TITLE
Style errors, no leaves drawn

### ISSUE THREAD

**Issue by whittaker007** [nazka/mapbox-gl-js-spiderfy#3]
I'm using maplibre-gl@2.1.9 and a layer that has a source set to cluster. The clustering works perfectly, but when I create a new simple spiderify and apply it to a cluster layer I get style validation errors when I click a cluster:

[Error] Error: layers.trap_clusters-spiderfy-leaf0.paint.circle-color: unknown property "circle-color" — validate_style.ts:42
[Error] Error: layers.trap_clusters-spiderfy-leaf0.paint.circle-color: unknown property "circle-radius" — validate_style.ts:42
[Error] Error: layers.trap_clusters-spiderfy-leaf0.paint.circle-color: unknown property "circle-stroke-width" — validate_style.ts:42
...
and so-on.

The clustering expansion still functions, and when I get to a cluster that should be spidered, it draws the spider lines, but does not draw any leaves at the ends of the spider lines.

**Comment by whittaker007** [comment]
Oh... does this only work with symbol markers, not circles? If so, is it possible to keep circle markers for the clusters but use symbol markers for the spidered leaves?

**Comment by simondriesen** [comment]
> Oh... does this only work with symbol markers, not circles?

We currently only support symbol markers indeed, supporting circle layers wasn't as straight forward as you might think so we decided to only support symbol layers for now. You can make symbols look like circles but that's all you can do for now sadly.

Thanks for the feedback though. I may look into supporting circle layers again in the future.
