### ISSUE TITLE
Browserify error

### ISSUE THREAD

**Issue by nijs9** [nazka/mapbox-gl-js-spiderfy#7]
When trying to create a browser js file with browserify i'm receiving this error:

ParseError: 'import' and 'export' may appear only with 'sourceType: module'

Is there any way to get a static js file to use this lib?

**Comment by simondriesen** [comment]
No experience with Browserify but maybe you need to add some config to it? https://stackoverflow.com/a/40029232/5333823

At the moment we only offer the npm package from which you should be able to retrieve the static js file in the dist folder. The `dist` folder with this static js file is git ignored on this repo but I may add it here if people find it useful.

Even when using this static js file it would still require the `color` dependency used in our plugin though so you will have to add it to your project as well.

**Comment by simondriesen** [comment]
`dist` folder has been removed from gitignore.
